/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#89f5e7',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container-highest': '#e3e1e9',
        'inverse-primary': '#b6c4ff',
        'surface-container-low': '#f4f3fa',
        'on-secondary': '#ffffff',
        'primary-container': '#1e3a8a',
        secondary: '#006a61',
        'tertiary-container': '#5c3800',
        background: '#faf8ff',
        'primary-fixed-dim': '#b6c4ff',
        'inverse-on-surface': '#f1f0f7',
        'surface-variant': '#e3e1e9',
        'outline-variant': '#c5c5d3',
        surface: '#faf8ff',
        'on-primary-container': '#90a8ff',
        'on-secondary-fixed': '#00201d',
        'surface-tint': '#4059aa',
        'on-surface-variant': '#444651',
        'on-tertiary-fixed': '#2a1700',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-container-high': '#e9e7ef',
        'surface-container': '#eeedf4',
        'on-secondary-fixed-variant': '#005049',
        tertiary: '#3e2400',
        'inverse-surface': '#2f3036',
        'secondary-fixed-dim': '#6bd8cb',
        'on-error': '#ffffff',
        outline: '#757682',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00164e',
        'on-tertiary-container': '#ef9900',
        'tertiary-fixed': '#ffddb8',
        'surface-bright': '#faf8ff',
        'on-secondary-container': '#006f66',
        'on-primary-fixed-variant': '#264191',
        'primary-fixed': '#dce1ff',
        'secondary-container': '#86f2e4',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb95f',
        'on-surface': '#1a1b21',
        'surface-container-lowest': '#ffffff',
        primary: '#00236f',
        'on-background': '#1a1b21',
        'surface-dim': '#dad9e1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'grid-columns': '12',
        gutter: '1.5rem',
        'space-lg': '1.5rem',
        'space-2xl': '3rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        code: ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        code: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}